# Generated by Django 4.2.6 on 2023-10-22 12:40

from django.db import migrations, models
import shortme.link.validators


class Migration(migrations.Migration):
    dependencies = [
        ("link", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortme",
            name="url",
            field=models.CharField(
                max_length=250,
                validators=[
                    shortme.link.validators.validate_url,
                    shortme.link.validators.validate_dot_com,
                ],
            ),
        ),
    ]
